[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["kobodump"]

[project]
name = "kobodump"
version = "0.0.1"
dependencies = [
    "click >= 8.1.3",
]

[project.scripts]
kobodump = "kobodump.kobodump:kobodump"